# Generated by Django 2.2.7 on 2019-11-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('position', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birthday', models.DateField()),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
